# Generated by Django 4.2.1 on 2023-05-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
